### ISSUE TITLE
please support merge libvirt0 and seabios in , if possible , can you merge virsh it :)

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Qemu_Appimage#10]

**Comment by lucasmz1** [comment]
ok I'll see what I can do, but I can't promise nothing.

**Comment by lucasmz1** [comment]
this link bellow you can find seabios for downloading already compiled.
https://www.seabios.org/Download

here is how to use it. it's a simple parameter -bios my_bios_file

https://stackoverflow.com/questions/10181899/qemu-launch-with-the-seabios

**Comment by lucasmz1** [comment]
about libvirt0 it's kinda complicated because it has a daemon which must be run from your machine, otherwise I cannot pack it. I've tried to that in my virt-manager.AppImage and didn't worked well.

**Comment by lucasmz1** [comment]
well I have enable libvirt0 to be compiled with qemu, I don't know if it will work. for now I am having an error on github actions during the compilation... wait for the next few days, the issue is related to a ppa that ubuntu 20.04 needs, as soon it get fixed I'll try to build the software with libvirt0 and virsh for you. hope you understand!

**Comment by lucasmz1** [comment]
Unfortunately I took it off, the reason why is because libvirt has a daemon called libvirtd which must start from your host os, and it doesnt work well in appimage, I know that because I have made an appimage from virt-manager and it's not working well because of this daemon. hope I have clear things up.
